//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/VehicleInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VehicleInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VehicleInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VehicleInputActions"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""3165492c-09f6-4833-a3da-0255ebcee1d5"",
            ""actions"": [
                {
                    ""name"": ""Steering"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9ac870d3-fc4a-4823-af27-033be7b5c295"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Braking"",
                    ""type"": ""Value"",
                    ""id"": ""60732a60-f93c-4182-8da6-b4606b15086e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Value"",
                    ""id"": ""0b6bfa0f-2068-4b47-9c52-13899dd4442d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Clutch"",
                    ""type"": ""Value"",
                    ""id"": ""2569e045-4d67-4d60-96fd-f06ae46828a4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StartEngine"",
                    ""type"": ""Button"",
                    ""id"": ""17f2383c-40db-40af-9e9c-0d5e70cd9243"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftUP"",
                    ""type"": ""Button"",
                    ""id"": ""b6945e8a-e13b-4e90-b12e-9b25b4e5bab8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftDOWN"",
                    ""type"": ""Button"",
                    ""id"": ""8dcb1d5e-7e88-4d08-8b8d-e2ae6403b12d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""18c0ef5e-0ed4-4b36-bd72-319c6d2532ea"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""638824c8-82fd-4909-9ae1-6a975cf14a66"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""56c92af4-5632-4cac-8074-a9a6765d54e8"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""ddfd05d0-8e54-4833-a145-bed3c5af1601"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c57a5c8b-fdff-41b0-ba83-d72125db3414"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""bc015404-74e5-4384-84cb-876171895a20"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c0cf47cc-cc89-464a-a430-248e4c65d582"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Braking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f790006-a774-41bd-bf51-7b97296e6029"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e5fa782-79a0-4d2f-b263-e58642a65c18"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartEngine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0448a37b-5f9a-439d-bca7-a037706ceba4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftUP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f137a5a-602a-46e8-a069-4de598e1ebc2"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftDOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SteeringWheel"",
            ""id"": ""ec4c0ef8-5c85-4345-8d74-cdbfbdb092f9"",
            ""actions"": [
                {
                    ""name"": ""Steering"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f434c636-5008-4afd-8c38-e77abeef483b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Braking"",
                    ""type"": ""Value"",
                    ""id"": ""68a923f8-44e1-4e47-8fee-d2f3528dc681"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Value"",
                    ""id"": ""12a87ce8-8051-43e0-bf3d-dee89cb079cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Clutch"",
                    ""type"": ""Value"",
                    ""id"": ""7f98a29f-feb3-47db-b37d-688837bb0ea9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StartEngine"",
                    ""type"": ""Button"",
                    ""id"": ""82cf9a1e-6f31-4058-86cc-0b815136baba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftUP"",
                    ""type"": ""Button"",
                    ""id"": ""c5197b52-0ad2-4968-8678-358dc9d4338e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftDOWN"",
                    ""type"": ""Button"",
                    ""id"": ""ce8ad70d-bcf7-4acb-a954-07b2932b8259"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""359f5655-a0f0-4412-ad70-b3d6cb2b1eb1"",
                    ""path"": ""<Logitech G HUB G29 Driving Force Racing Wheel USB•{80441800-D376-11EB-8003-444553540000}>/X"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""984446b7-2492-4326-b007-85c550ed98cd"",
                    ""path"": ""<Logitech G HUB G29 Driving Force Racing Wheel USB•{80441800-D376-11EB-8003-444553540000}>/RZ"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Braking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cea6fee-c649-49b0-86f3-232d91c50d24"",
                    ""path"": ""<Logitech G HUB G29 Driving Force Racing Wheel USB•{80441800-D376-11EB-8003-444553540000}>/Y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa404ff1-814b-451b-a2f4-aad3281f2826"",
                    ""path"": ""<Logitech G HUB G29 Driving Force Racing Wheel USB•{80441800-D376-11EB-8003-444553540000}>/Button004"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftUP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e23b331-85f6-4105-b582-196f3e0deb40"",
                    ""path"": ""<Logitech G HUB G29 Driving Force Racing Wheel USB•{80441800-D376-11EB-8003-444553540000}>/Button005"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftDOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_Steering = m_Default.FindAction("Steering", throwIfNotFound: true);
        m_Default_Braking = m_Default.FindAction("Braking", throwIfNotFound: true);
        m_Default_Acceleration = m_Default.FindAction("Acceleration", throwIfNotFound: true);
        m_Default_Clutch = m_Default.FindAction("Clutch", throwIfNotFound: true);
        m_Default_StartEngine = m_Default.FindAction("StartEngine", throwIfNotFound: true);
        m_Default_ShiftUP = m_Default.FindAction("ShiftUP", throwIfNotFound: true);
        m_Default_ShiftDOWN = m_Default.FindAction("ShiftDOWN", throwIfNotFound: true);
        // SteeringWheel
        m_SteeringWheel = asset.FindActionMap("SteeringWheel", throwIfNotFound: true);
        m_SteeringWheel_Steering = m_SteeringWheel.FindAction("Steering", throwIfNotFound: true);
        m_SteeringWheel_Braking = m_SteeringWheel.FindAction("Braking", throwIfNotFound: true);
        m_SteeringWheel_Acceleration = m_SteeringWheel.FindAction("Acceleration", throwIfNotFound: true);
        m_SteeringWheel_Clutch = m_SteeringWheel.FindAction("Clutch", throwIfNotFound: true);
        m_SteeringWheel_StartEngine = m_SteeringWheel.FindAction("StartEngine", throwIfNotFound: true);
        m_SteeringWheel_ShiftUP = m_SteeringWheel.FindAction("ShiftUP", throwIfNotFound: true);
        m_SteeringWheel_ShiftDOWN = m_SteeringWheel.FindAction("ShiftDOWN", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private IDefaultActions m_DefaultActionsCallbackInterface;
    private readonly InputAction m_Default_Steering;
    private readonly InputAction m_Default_Braking;
    private readonly InputAction m_Default_Acceleration;
    private readonly InputAction m_Default_Clutch;
    private readonly InputAction m_Default_StartEngine;
    private readonly InputAction m_Default_ShiftUP;
    private readonly InputAction m_Default_ShiftDOWN;
    public struct DefaultActions
    {
        private @VehicleInputActions m_Wrapper;
        public DefaultActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Steering => m_Wrapper.m_Default_Steering;
        public InputAction @Braking => m_Wrapper.m_Default_Braking;
        public InputAction @Acceleration => m_Wrapper.m_Default_Acceleration;
        public InputAction @Clutch => m_Wrapper.m_Default_Clutch;
        public InputAction @StartEngine => m_Wrapper.m_Default_StartEngine;
        public InputAction @ShiftUP => m_Wrapper.m_Default_ShiftUP;
        public InputAction @ShiftDOWN => m_Wrapper.m_Default_ShiftDOWN;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterface != null)
            {
                @Steering.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSteering;
                @Steering.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSteering;
                @Steering.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSteering;
                @Braking.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnBraking;
                @Braking.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnBraking;
                @Braking.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnBraking;
                @Acceleration.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnAcceleration;
                @Acceleration.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnAcceleration;
                @Acceleration.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnAcceleration;
                @Clutch.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnClutch;
                @Clutch.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnClutch;
                @Clutch.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnClutch;
                @StartEngine.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnStartEngine;
                @StartEngine.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnStartEngine;
                @StartEngine.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnStartEngine;
                @ShiftUP.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnShiftUP;
                @ShiftUP.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnShiftUP;
                @ShiftUP.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnShiftUP;
                @ShiftDOWN.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnShiftDOWN;
            }
            m_Wrapper.m_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Steering.started += instance.OnSteering;
                @Steering.performed += instance.OnSteering;
                @Steering.canceled += instance.OnSteering;
                @Braking.started += instance.OnBraking;
                @Braking.performed += instance.OnBraking;
                @Braking.canceled += instance.OnBraking;
                @Acceleration.started += instance.OnAcceleration;
                @Acceleration.performed += instance.OnAcceleration;
                @Acceleration.canceled += instance.OnAcceleration;
                @Clutch.started += instance.OnClutch;
                @Clutch.performed += instance.OnClutch;
                @Clutch.canceled += instance.OnClutch;
                @StartEngine.started += instance.OnStartEngine;
                @StartEngine.performed += instance.OnStartEngine;
                @StartEngine.canceled += instance.OnStartEngine;
                @ShiftUP.started += instance.OnShiftUP;
                @ShiftUP.performed += instance.OnShiftUP;
                @ShiftUP.canceled += instance.OnShiftUP;
                @ShiftDOWN.started += instance.OnShiftDOWN;
                @ShiftDOWN.performed += instance.OnShiftDOWN;
                @ShiftDOWN.canceled += instance.OnShiftDOWN;
            }
        }
    }
    public DefaultActions @Default => new DefaultActions(this);

    // SteeringWheel
    private readonly InputActionMap m_SteeringWheel;
    private ISteeringWheelActions m_SteeringWheelActionsCallbackInterface;
    private readonly InputAction m_SteeringWheel_Steering;
    private readonly InputAction m_SteeringWheel_Braking;
    private readonly InputAction m_SteeringWheel_Acceleration;
    private readonly InputAction m_SteeringWheel_Clutch;
    private readonly InputAction m_SteeringWheel_StartEngine;
    private readonly InputAction m_SteeringWheel_ShiftUP;
    private readonly InputAction m_SteeringWheel_ShiftDOWN;
    public struct SteeringWheelActions
    {
        private @VehicleInputActions m_Wrapper;
        public SteeringWheelActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Steering => m_Wrapper.m_SteeringWheel_Steering;
        public InputAction @Braking => m_Wrapper.m_SteeringWheel_Braking;
        public InputAction @Acceleration => m_Wrapper.m_SteeringWheel_Acceleration;
        public InputAction @Clutch => m_Wrapper.m_SteeringWheel_Clutch;
        public InputAction @StartEngine => m_Wrapper.m_SteeringWheel_StartEngine;
        public InputAction @ShiftUP => m_Wrapper.m_SteeringWheel_ShiftUP;
        public InputAction @ShiftDOWN => m_Wrapper.m_SteeringWheel_ShiftDOWN;
        public InputActionMap Get() { return m_Wrapper.m_SteeringWheel; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SteeringWheelActions set) { return set.Get(); }
        public void SetCallbacks(ISteeringWheelActions instance)
        {
            if (m_Wrapper.m_SteeringWheelActionsCallbackInterface != null)
            {
                @Steering.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnSteering;
                @Steering.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnSteering;
                @Steering.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnSteering;
                @Braking.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnBraking;
                @Braking.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnBraking;
                @Braking.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnBraking;
                @Acceleration.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnAcceleration;
                @Acceleration.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnAcceleration;
                @Acceleration.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnAcceleration;
                @Clutch.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnClutch;
                @Clutch.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnClutch;
                @Clutch.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnClutch;
                @StartEngine.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnStartEngine;
                @StartEngine.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnStartEngine;
                @StartEngine.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnStartEngine;
                @ShiftUP.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftUP;
                @ShiftUP.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftUP;
                @ShiftUP.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftUP;
                @ShiftDOWN.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftDOWN;
            }
            m_Wrapper.m_SteeringWheelActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Steering.started += instance.OnSteering;
                @Steering.performed += instance.OnSteering;
                @Steering.canceled += instance.OnSteering;
                @Braking.started += instance.OnBraking;
                @Braking.performed += instance.OnBraking;
                @Braking.canceled += instance.OnBraking;
                @Acceleration.started += instance.OnAcceleration;
                @Acceleration.performed += instance.OnAcceleration;
                @Acceleration.canceled += instance.OnAcceleration;
                @Clutch.started += instance.OnClutch;
                @Clutch.performed += instance.OnClutch;
                @Clutch.canceled += instance.OnClutch;
                @StartEngine.started += instance.OnStartEngine;
                @StartEngine.performed += instance.OnStartEngine;
                @StartEngine.canceled += instance.OnStartEngine;
                @ShiftUP.started += instance.OnShiftUP;
                @ShiftUP.performed += instance.OnShiftUP;
                @ShiftUP.canceled += instance.OnShiftUP;
                @ShiftDOWN.started += instance.OnShiftDOWN;
                @ShiftDOWN.performed += instance.OnShiftDOWN;
                @ShiftDOWN.canceled += instance.OnShiftDOWN;
            }
        }
    }
    public SteeringWheelActions @SteeringWheel => new SteeringWheelActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IDefaultActions
    {
        void OnSteering(InputAction.CallbackContext context);
        void OnBraking(InputAction.CallbackContext context);
        void OnAcceleration(InputAction.CallbackContext context);
        void OnClutch(InputAction.CallbackContext context);
        void OnStartEngine(InputAction.CallbackContext context);
        void OnShiftUP(InputAction.CallbackContext context);
        void OnShiftDOWN(InputAction.CallbackContext context);
    }
    public interface ISteeringWheelActions
    {
        void OnSteering(InputAction.CallbackContext context);
        void OnBraking(InputAction.CallbackContext context);
        void OnAcceleration(InputAction.CallbackContext context);
        void OnClutch(InputAction.CallbackContext context);
        void OnStartEngine(InputAction.CallbackContext context);
        void OnShiftUP(InputAction.CallbackContext context);
        void OnShiftDOWN(InputAction.CallbackContext context);
    }
}
