//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/VehicleInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @VehicleInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @VehicleInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""VehicleInputActions"",
    ""maps"": [
        {
            ""name"": ""Keyboard"",
            ""id"": ""3165492c-09f6-4833-a3da-0255ebcee1d5"",
            ""actions"": [
                {
                    ""name"": ""Steering"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9ac870d3-fc4a-4823-af27-033be7b5c295"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Braking"",
                    ""type"": ""Value"",
                    ""id"": ""60732a60-f93c-4182-8da6-b4606b15086e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Value"",
                    ""id"": ""0b6bfa0f-2068-4b47-9c52-13899dd4442d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Clutch"",
                    ""type"": ""Value"",
                    ""id"": ""2569e045-4d67-4d60-96fd-f06ae46828a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ShiftUP"",
                    ""type"": ""Button"",
                    ""id"": ""b6945e8a-e13b-4e90-b12e-9b25b4e5bab8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftDOWN"",
                    ""type"": ""Button"",
                    ""id"": ""8dcb1d5e-7e88-4d08-8b8d-e2ae6403b12d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""ec853118-76d7-4a23-abae-026f9228c6ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartEngine"",
                    ""type"": ""Button"",
                    ""id"": ""17f2383c-40db-40af-9e9c-0d5e70cd9243"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MinimapRescale"",
                    ""type"": ""Button"",
                    ""id"": ""1eb7ee98-a88e-4f78-9f8d-337a5b32eb00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextRadioSong"",
                    ""type"": ""Button"",
                    ""id"": ""58343f64-6a60-4986-b4f9-635ba7785d2e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseRadio"",
                    ""type"": ""Button"",
                    ""id"": ""80fc5b20-739b-4a16-a31c-e5486cf0cb48"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""18c0ef5e-0ed4-4b36-bd72-319c6d2532ea"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""638824c8-82fd-4909-9ae1-6a975cf14a66"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""56c92af4-5632-4cac-8074-a9a6765d54e8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c0cf47cc-cc89-464a-a430-248e4c65d582"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Braking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f790006-a774-41bd-bf51-7b97296e6029"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0448a37b-5f9a-439d-bca7-a037706ceba4"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftUP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f137a5a-602a-46e8-a069-4de598e1ebc2"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftDOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""886e6d23-9e88-4be8-ba1a-768402723e90"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clutch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6b113de5-db00-4afd-ba39-ef3ee3e8e67e"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e5fa782-79a0-4d2f-b263-e58642a65c18"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartEngine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e31aa3e9-2ab7-462e-967c-4d8c7b9336f8"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinimapRescale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c48717f-d6d1-4d88-87af-6501aa15da0d"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextRadioSong"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ca7a10b-ebf9-4935-a21f-05896a84a73b"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseRadio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""id"": ""b6f20142-5f47-4e29-b5c6-e29862b4c043"",
            ""actions"": [
                {
                    ""name"": ""Steering"",
                    ""type"": ""Value"",
                    ""id"": ""12bf9210-637f-438a-9029-a567cc364ab3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Braking"",
                    ""type"": ""Value"",
                    ""id"": ""df5d435f-85ec-49ec-9833-7a7e7fe2940d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Value"",
                    ""id"": ""d74d4e45-a706-4f08-8727-b82dfc3457fb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Clutch"",
                    ""type"": ""Value"",
                    ""id"": ""dedb4ce9-0f13-4927-978f-5218631f353a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ShiftUP"",
                    ""type"": ""Button"",
                    ""id"": ""2048bd72-6c86-4bca-b68a-926a24916af9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftDOWN"",
                    ""type"": ""Button"",
                    ""id"": ""3775a6d1-421f-4d71-af3e-232b6e9da39e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""bd85a2fc-88a7-48eb-b2ed-cfffec9ff924"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartEngine"",
                    ""type"": ""Button"",
                    ""id"": ""1c6ecb50-4e95-4829-998c-67ed0c0c7100"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MinimapRescale"",
                    ""type"": ""Button"",
                    ""id"": ""f664c7e2-b1d8-4fb2-9383-9e48da108a25"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextRadioSong"",
                    ""type"": ""Button"",
                    ""id"": ""001e8b28-0e1b-48b4-a9ea-d264a755d02e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseRadio"",
                    ""type"": ""Button"",
                    ""id"": ""a2b96021-661d-4c78-a93b-5fec8cab81b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fff29810-ecfd-4c45-acef-9ac8909c82cc"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Braking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b470d966-d091-43f6-a042-ee7dc2439292"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ce73d3b-323f-4a9d-8f9f-8ae3877344e8"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftUP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54ffeb16-1ba8-4471-a218-99832f24aed1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftDOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c887497-ebd5-4128-8036-e7e070b9d109"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clutch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd5e5ad6-a061-4876-8609-f3f202cbc381"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2f2be14-2750-46a1-a573-9354bbe190f1"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartEngine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a092d08a-3c1f-4f87-94b5-6ea93a8d7f62"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0d09693c-d495-48c4-93f8-c3e8800dbcef"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7e68af28-8228-41dd-bce0-71f041467643"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7e024d82-ddab-4efd-a077-40c0129d2fc6"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinimapRescale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5a96fb5-da21-490a-9b0b-ddac217dc877"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextRadioSong"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85edfc63-4c6e-4d56-b64c-19317726d20e"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseRadio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SteeringWheel"",
            ""id"": ""ec4c0ef8-5c85-4345-8d74-cdbfbdb092f9"",
            ""actions"": [
                {
                    ""name"": ""Steering"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f434c636-5008-4afd-8c38-e77abeef483b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Braking"",
                    ""type"": ""Value"",
                    ""id"": ""68a923f8-44e1-4e47-8fee-d2f3528dc681"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Value"",
                    ""id"": ""12a87ce8-8051-43e0-bf3d-dee89cb079cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Clutch"",
                    ""type"": ""Value"",
                    ""id"": ""7f98a29f-feb3-47db-b37d-688837bb0ea9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ShiftUP"",
                    ""type"": ""Button"",
                    ""id"": ""c5197b52-0ad2-4968-8678-358dc9d4338e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShiftDOWN"",
                    ""type"": ""Button"",
                    ""id"": ""ce8ad70d-bcf7-4acb-a954-07b2932b8259"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""13bf80e8-7e00-4e7c-8595-752e04f5d5ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartEngine"",
                    ""type"": ""Button"",
                    ""id"": ""82cf9a1e-6f31-4058-86cc-0b815136baba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MinimapRescale"",
                    ""type"": ""Button"",
                    ""id"": ""0b10ad29-be02-4272-99db-4cd37bcd5de4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextRadioSong"",
                    ""type"": ""Button"",
                    ""id"": ""f6f923e4-505d-420a-a48f-5c8ca29417f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseRadio"",
                    ""type"": ""Button"",
                    ""id"": ""74574e1a-bd84-4e9c-9832-291bece72e04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""359f5655-a0f0-4412-ad70-b3d6cb2b1eb1"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steering"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""984446b7-2492-4326-b007-85c550ed98cd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Braking"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cea6fee-c649-49b0-86f3-232d91c50d24"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa404ff1-814b-451b-a2f4-aad3281f2826"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftUP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e23b331-85f6-4105-b582-196f3e0deb40"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShiftDOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c9424dd-39b1-4f16-876d-a5ca77b8b8d6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clutch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9e230aa-1ab7-4a07-ade3-239a621ad055"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14151374-08dc-4395-bdc2-5d3372cb2c56"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartEngine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c160323b-acd0-4ec6-8cd0-e9e23d667969"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinimapRescale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab846ec9-5ffc-4743-8af9-f54539ab98e5"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextRadioSong"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cec4135-6c83-4888-a6e8-63837ebeecee"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseRadio"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Keyboard
        m_Keyboard = asset.FindActionMap("Keyboard", throwIfNotFound: true);
        m_Keyboard_Steering = m_Keyboard.FindAction("Steering", throwIfNotFound: true);
        m_Keyboard_Braking = m_Keyboard.FindAction("Braking", throwIfNotFound: true);
        m_Keyboard_Acceleration = m_Keyboard.FindAction("Acceleration", throwIfNotFound: true);
        m_Keyboard_Clutch = m_Keyboard.FindAction("Clutch", throwIfNotFound: true);
        m_Keyboard_ShiftUP = m_Keyboard.FindAction("ShiftUP", throwIfNotFound: true);
        m_Keyboard_ShiftDOWN = m_Keyboard.FindAction("ShiftDOWN", throwIfNotFound: true);
        m_Keyboard_Reset = m_Keyboard.FindAction("Reset", throwIfNotFound: true);
        m_Keyboard_StartEngine = m_Keyboard.FindAction("StartEngine", throwIfNotFound: true);
        m_Keyboard_MinimapRescale = m_Keyboard.FindAction("MinimapRescale", throwIfNotFound: true);
        m_Keyboard_NextRadioSong = m_Keyboard.FindAction("NextRadioSong", throwIfNotFound: true);
        m_Keyboard_PauseRadio = m_Keyboard.FindAction("PauseRadio", throwIfNotFound: true);
        // Gamepad
        m_Gamepad = asset.FindActionMap("Gamepad", throwIfNotFound: true);
        m_Gamepad_Steering = m_Gamepad.FindAction("Steering", throwIfNotFound: true);
        m_Gamepad_Braking = m_Gamepad.FindAction("Braking", throwIfNotFound: true);
        m_Gamepad_Acceleration = m_Gamepad.FindAction("Acceleration", throwIfNotFound: true);
        m_Gamepad_Clutch = m_Gamepad.FindAction("Clutch", throwIfNotFound: true);
        m_Gamepad_ShiftUP = m_Gamepad.FindAction("ShiftUP", throwIfNotFound: true);
        m_Gamepad_ShiftDOWN = m_Gamepad.FindAction("ShiftDOWN", throwIfNotFound: true);
        m_Gamepad_Reset = m_Gamepad.FindAction("Reset", throwIfNotFound: true);
        m_Gamepad_StartEngine = m_Gamepad.FindAction("StartEngine", throwIfNotFound: true);
        m_Gamepad_MinimapRescale = m_Gamepad.FindAction("MinimapRescale", throwIfNotFound: true);
        m_Gamepad_NextRadioSong = m_Gamepad.FindAction("NextRadioSong", throwIfNotFound: true);
        m_Gamepad_PauseRadio = m_Gamepad.FindAction("PauseRadio", throwIfNotFound: true);
        // SteeringWheel
        m_SteeringWheel = asset.FindActionMap("SteeringWheel", throwIfNotFound: true);
        m_SteeringWheel_Steering = m_SteeringWheel.FindAction("Steering", throwIfNotFound: true);
        m_SteeringWheel_Braking = m_SteeringWheel.FindAction("Braking", throwIfNotFound: true);
        m_SteeringWheel_Acceleration = m_SteeringWheel.FindAction("Acceleration", throwIfNotFound: true);
        m_SteeringWheel_Clutch = m_SteeringWheel.FindAction("Clutch", throwIfNotFound: true);
        m_SteeringWheel_ShiftUP = m_SteeringWheel.FindAction("ShiftUP", throwIfNotFound: true);
        m_SteeringWheel_ShiftDOWN = m_SteeringWheel.FindAction("ShiftDOWN", throwIfNotFound: true);
        m_SteeringWheel_Reset = m_SteeringWheel.FindAction("Reset", throwIfNotFound: true);
        m_SteeringWheel_StartEngine = m_SteeringWheel.FindAction("StartEngine", throwIfNotFound: true);
        m_SteeringWheel_MinimapRescale = m_SteeringWheel.FindAction("MinimapRescale", throwIfNotFound: true);
        m_SteeringWheel_NextRadioSong = m_SteeringWheel.FindAction("NextRadioSong", throwIfNotFound: true);
        m_SteeringWheel_PauseRadio = m_SteeringWheel.FindAction("PauseRadio", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Keyboard
    private readonly InputActionMap m_Keyboard;
    private IKeyboardActions m_KeyboardActionsCallbackInterface;
    private readonly InputAction m_Keyboard_Steering;
    private readonly InputAction m_Keyboard_Braking;
    private readonly InputAction m_Keyboard_Acceleration;
    private readonly InputAction m_Keyboard_Clutch;
    private readonly InputAction m_Keyboard_ShiftUP;
    private readonly InputAction m_Keyboard_ShiftDOWN;
    private readonly InputAction m_Keyboard_Reset;
    private readonly InputAction m_Keyboard_StartEngine;
    private readonly InputAction m_Keyboard_MinimapRescale;
    private readonly InputAction m_Keyboard_NextRadioSong;
    private readonly InputAction m_Keyboard_PauseRadio;
    public struct KeyboardActions
    {
        private @VehicleInputActions m_Wrapper;
        public KeyboardActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Steering => m_Wrapper.m_Keyboard_Steering;
        public InputAction @Braking => m_Wrapper.m_Keyboard_Braking;
        public InputAction @Acceleration => m_Wrapper.m_Keyboard_Acceleration;
        public InputAction @Clutch => m_Wrapper.m_Keyboard_Clutch;
        public InputAction @ShiftUP => m_Wrapper.m_Keyboard_ShiftUP;
        public InputAction @ShiftDOWN => m_Wrapper.m_Keyboard_ShiftDOWN;
        public InputAction @Reset => m_Wrapper.m_Keyboard_Reset;
        public InputAction @StartEngine => m_Wrapper.m_Keyboard_StartEngine;
        public InputAction @MinimapRescale => m_Wrapper.m_Keyboard_MinimapRescale;
        public InputAction @NextRadioSong => m_Wrapper.m_Keyboard_NextRadioSong;
        public InputAction @PauseRadio => m_Wrapper.m_Keyboard_PauseRadio;
        public InputActionMap Get() { return m_Wrapper.m_Keyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
        public void SetCallbacks(IKeyboardActions instance)
        {
            if (m_Wrapper.m_KeyboardActionsCallbackInterface != null)
            {
                @Steering.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnSteering;
                @Steering.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnSteering;
                @Steering.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnSteering;
                @Braking.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnBraking;
                @Braking.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnBraking;
                @Braking.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnBraking;
                @Acceleration.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAcceleration;
                @Acceleration.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAcceleration;
                @Acceleration.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAcceleration;
                @Clutch.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnClutch;
                @Clutch.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnClutch;
                @Clutch.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnClutch;
                @ShiftUP.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnShiftUP;
                @ShiftUP.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnShiftUP;
                @ShiftUP.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnShiftUP;
                @ShiftDOWN.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnShiftDOWN;
                @Reset.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnReset;
                @Reset.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnReset;
                @Reset.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnReset;
                @StartEngine.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnStartEngine;
                @StartEngine.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnStartEngine;
                @StartEngine.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnStartEngine;
                @MinimapRescale.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnMinimapRescale;
                @MinimapRescale.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnMinimapRescale;
                @MinimapRescale.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnMinimapRescale;
                @NextRadioSong.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnNextRadioSong;
                @NextRadioSong.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnNextRadioSong;
                @NextRadioSong.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnNextRadioSong;
                @PauseRadio.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnPauseRadio;
                @PauseRadio.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnPauseRadio;
                @PauseRadio.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnPauseRadio;
            }
            m_Wrapper.m_KeyboardActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Steering.started += instance.OnSteering;
                @Steering.performed += instance.OnSteering;
                @Steering.canceled += instance.OnSteering;
                @Braking.started += instance.OnBraking;
                @Braking.performed += instance.OnBraking;
                @Braking.canceled += instance.OnBraking;
                @Acceleration.started += instance.OnAcceleration;
                @Acceleration.performed += instance.OnAcceleration;
                @Acceleration.canceled += instance.OnAcceleration;
                @Clutch.started += instance.OnClutch;
                @Clutch.performed += instance.OnClutch;
                @Clutch.canceled += instance.OnClutch;
                @ShiftUP.started += instance.OnShiftUP;
                @ShiftUP.performed += instance.OnShiftUP;
                @ShiftUP.canceled += instance.OnShiftUP;
                @ShiftDOWN.started += instance.OnShiftDOWN;
                @ShiftDOWN.performed += instance.OnShiftDOWN;
                @ShiftDOWN.canceled += instance.OnShiftDOWN;
                @Reset.started += instance.OnReset;
                @Reset.performed += instance.OnReset;
                @Reset.canceled += instance.OnReset;
                @StartEngine.started += instance.OnStartEngine;
                @StartEngine.performed += instance.OnStartEngine;
                @StartEngine.canceled += instance.OnStartEngine;
                @MinimapRescale.started += instance.OnMinimapRescale;
                @MinimapRescale.performed += instance.OnMinimapRescale;
                @MinimapRescale.canceled += instance.OnMinimapRescale;
                @NextRadioSong.started += instance.OnNextRadioSong;
                @NextRadioSong.performed += instance.OnNextRadioSong;
                @NextRadioSong.canceled += instance.OnNextRadioSong;
                @PauseRadio.started += instance.OnPauseRadio;
                @PauseRadio.performed += instance.OnPauseRadio;
                @PauseRadio.canceled += instance.OnPauseRadio;
            }
        }
    }
    public KeyboardActions @Keyboard => new KeyboardActions(this);

    // Gamepad
    private readonly InputActionMap m_Gamepad;
    private IGamepadActions m_GamepadActionsCallbackInterface;
    private readonly InputAction m_Gamepad_Steering;
    private readonly InputAction m_Gamepad_Braking;
    private readonly InputAction m_Gamepad_Acceleration;
    private readonly InputAction m_Gamepad_Clutch;
    private readonly InputAction m_Gamepad_ShiftUP;
    private readonly InputAction m_Gamepad_ShiftDOWN;
    private readonly InputAction m_Gamepad_Reset;
    private readonly InputAction m_Gamepad_StartEngine;
    private readonly InputAction m_Gamepad_MinimapRescale;
    private readonly InputAction m_Gamepad_NextRadioSong;
    private readonly InputAction m_Gamepad_PauseRadio;
    public struct GamepadActions
    {
        private @VehicleInputActions m_Wrapper;
        public GamepadActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Steering => m_Wrapper.m_Gamepad_Steering;
        public InputAction @Braking => m_Wrapper.m_Gamepad_Braking;
        public InputAction @Acceleration => m_Wrapper.m_Gamepad_Acceleration;
        public InputAction @Clutch => m_Wrapper.m_Gamepad_Clutch;
        public InputAction @ShiftUP => m_Wrapper.m_Gamepad_ShiftUP;
        public InputAction @ShiftDOWN => m_Wrapper.m_Gamepad_ShiftDOWN;
        public InputAction @Reset => m_Wrapper.m_Gamepad_Reset;
        public InputAction @StartEngine => m_Wrapper.m_Gamepad_StartEngine;
        public InputAction @MinimapRescale => m_Wrapper.m_Gamepad_MinimapRescale;
        public InputAction @NextRadioSong => m_Wrapper.m_Gamepad_NextRadioSong;
        public InputAction @PauseRadio => m_Wrapper.m_Gamepad_PauseRadio;
        public InputActionMap Get() { return m_Wrapper.m_Gamepad; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamepadActions set) { return set.Get(); }
        public void SetCallbacks(IGamepadActions instance)
        {
            if (m_Wrapper.m_GamepadActionsCallbackInterface != null)
            {
                @Steering.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnSteering;
                @Steering.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnSteering;
                @Steering.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnSteering;
                @Braking.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnBraking;
                @Braking.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnBraking;
                @Braking.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnBraking;
                @Acceleration.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnAcceleration;
                @Acceleration.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnAcceleration;
                @Acceleration.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnAcceleration;
                @Clutch.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnClutch;
                @Clutch.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnClutch;
                @Clutch.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnClutch;
                @ShiftUP.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnShiftUP;
                @ShiftUP.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnShiftUP;
                @ShiftUP.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnShiftUP;
                @ShiftDOWN.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnShiftDOWN;
                @Reset.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnReset;
                @Reset.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnReset;
                @Reset.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnReset;
                @StartEngine.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnStartEngine;
                @StartEngine.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnStartEngine;
                @StartEngine.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnStartEngine;
                @MinimapRescale.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnMinimapRescale;
                @MinimapRescale.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnMinimapRescale;
                @MinimapRescale.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnMinimapRescale;
                @NextRadioSong.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnNextRadioSong;
                @NextRadioSong.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnNextRadioSong;
                @NextRadioSong.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnNextRadioSong;
                @PauseRadio.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnPauseRadio;
                @PauseRadio.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnPauseRadio;
                @PauseRadio.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnPauseRadio;
            }
            m_Wrapper.m_GamepadActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Steering.started += instance.OnSteering;
                @Steering.performed += instance.OnSteering;
                @Steering.canceled += instance.OnSteering;
                @Braking.started += instance.OnBraking;
                @Braking.performed += instance.OnBraking;
                @Braking.canceled += instance.OnBraking;
                @Acceleration.started += instance.OnAcceleration;
                @Acceleration.performed += instance.OnAcceleration;
                @Acceleration.canceled += instance.OnAcceleration;
                @Clutch.started += instance.OnClutch;
                @Clutch.performed += instance.OnClutch;
                @Clutch.canceled += instance.OnClutch;
                @ShiftUP.started += instance.OnShiftUP;
                @ShiftUP.performed += instance.OnShiftUP;
                @ShiftUP.canceled += instance.OnShiftUP;
                @ShiftDOWN.started += instance.OnShiftDOWN;
                @ShiftDOWN.performed += instance.OnShiftDOWN;
                @ShiftDOWN.canceled += instance.OnShiftDOWN;
                @Reset.started += instance.OnReset;
                @Reset.performed += instance.OnReset;
                @Reset.canceled += instance.OnReset;
                @StartEngine.started += instance.OnStartEngine;
                @StartEngine.performed += instance.OnStartEngine;
                @StartEngine.canceled += instance.OnStartEngine;
                @MinimapRescale.started += instance.OnMinimapRescale;
                @MinimapRescale.performed += instance.OnMinimapRescale;
                @MinimapRescale.canceled += instance.OnMinimapRescale;
                @NextRadioSong.started += instance.OnNextRadioSong;
                @NextRadioSong.performed += instance.OnNextRadioSong;
                @NextRadioSong.canceled += instance.OnNextRadioSong;
                @PauseRadio.started += instance.OnPauseRadio;
                @PauseRadio.performed += instance.OnPauseRadio;
                @PauseRadio.canceled += instance.OnPauseRadio;
            }
        }
    }
    public GamepadActions @Gamepad => new GamepadActions(this);

    // SteeringWheel
    private readonly InputActionMap m_SteeringWheel;
    private ISteeringWheelActions m_SteeringWheelActionsCallbackInterface;
    private readonly InputAction m_SteeringWheel_Steering;
    private readonly InputAction m_SteeringWheel_Braking;
    private readonly InputAction m_SteeringWheel_Acceleration;
    private readonly InputAction m_SteeringWheel_Clutch;
    private readonly InputAction m_SteeringWheel_ShiftUP;
    private readonly InputAction m_SteeringWheel_ShiftDOWN;
    private readonly InputAction m_SteeringWheel_Reset;
    private readonly InputAction m_SteeringWheel_StartEngine;
    private readonly InputAction m_SteeringWheel_MinimapRescale;
    private readonly InputAction m_SteeringWheel_NextRadioSong;
    private readonly InputAction m_SteeringWheel_PauseRadio;
    public struct SteeringWheelActions
    {
        private @VehicleInputActions m_Wrapper;
        public SteeringWheelActions(@VehicleInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Steering => m_Wrapper.m_SteeringWheel_Steering;
        public InputAction @Braking => m_Wrapper.m_SteeringWheel_Braking;
        public InputAction @Acceleration => m_Wrapper.m_SteeringWheel_Acceleration;
        public InputAction @Clutch => m_Wrapper.m_SteeringWheel_Clutch;
        public InputAction @ShiftUP => m_Wrapper.m_SteeringWheel_ShiftUP;
        public InputAction @ShiftDOWN => m_Wrapper.m_SteeringWheel_ShiftDOWN;
        public InputAction @Reset => m_Wrapper.m_SteeringWheel_Reset;
        public InputAction @StartEngine => m_Wrapper.m_SteeringWheel_StartEngine;
        public InputAction @MinimapRescale => m_Wrapper.m_SteeringWheel_MinimapRescale;
        public InputAction @NextRadioSong => m_Wrapper.m_SteeringWheel_NextRadioSong;
        public InputAction @PauseRadio => m_Wrapper.m_SteeringWheel_PauseRadio;
        public InputActionMap Get() { return m_Wrapper.m_SteeringWheel; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SteeringWheelActions set) { return set.Get(); }
        public void SetCallbacks(ISteeringWheelActions instance)
        {
            if (m_Wrapper.m_SteeringWheelActionsCallbackInterface != null)
            {
                @Steering.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnSteering;
                @Steering.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnSteering;
                @Steering.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnSteering;
                @Braking.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnBraking;
                @Braking.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnBraking;
                @Braking.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnBraking;
                @Acceleration.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnAcceleration;
                @Acceleration.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnAcceleration;
                @Acceleration.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnAcceleration;
                @Clutch.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnClutch;
                @Clutch.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnClutch;
                @Clutch.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnClutch;
                @ShiftUP.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftUP;
                @ShiftUP.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftUP;
                @ShiftUP.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftUP;
                @ShiftDOWN.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftDOWN;
                @ShiftDOWN.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnShiftDOWN;
                @Reset.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnReset;
                @Reset.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnReset;
                @Reset.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnReset;
                @StartEngine.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnStartEngine;
                @StartEngine.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnStartEngine;
                @StartEngine.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnStartEngine;
                @MinimapRescale.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnMinimapRescale;
                @MinimapRescale.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnMinimapRescale;
                @MinimapRescale.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnMinimapRescale;
                @NextRadioSong.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnNextRadioSong;
                @NextRadioSong.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnNextRadioSong;
                @NextRadioSong.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnNextRadioSong;
                @PauseRadio.started -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnPauseRadio;
                @PauseRadio.performed -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnPauseRadio;
                @PauseRadio.canceled -= m_Wrapper.m_SteeringWheelActionsCallbackInterface.OnPauseRadio;
            }
            m_Wrapper.m_SteeringWheelActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Steering.started += instance.OnSteering;
                @Steering.performed += instance.OnSteering;
                @Steering.canceled += instance.OnSteering;
                @Braking.started += instance.OnBraking;
                @Braking.performed += instance.OnBraking;
                @Braking.canceled += instance.OnBraking;
                @Acceleration.started += instance.OnAcceleration;
                @Acceleration.performed += instance.OnAcceleration;
                @Acceleration.canceled += instance.OnAcceleration;
                @Clutch.started += instance.OnClutch;
                @Clutch.performed += instance.OnClutch;
                @Clutch.canceled += instance.OnClutch;
                @ShiftUP.started += instance.OnShiftUP;
                @ShiftUP.performed += instance.OnShiftUP;
                @ShiftUP.canceled += instance.OnShiftUP;
                @ShiftDOWN.started += instance.OnShiftDOWN;
                @ShiftDOWN.performed += instance.OnShiftDOWN;
                @ShiftDOWN.canceled += instance.OnShiftDOWN;
                @Reset.started += instance.OnReset;
                @Reset.performed += instance.OnReset;
                @Reset.canceled += instance.OnReset;
                @StartEngine.started += instance.OnStartEngine;
                @StartEngine.performed += instance.OnStartEngine;
                @StartEngine.canceled += instance.OnStartEngine;
                @MinimapRescale.started += instance.OnMinimapRescale;
                @MinimapRescale.performed += instance.OnMinimapRescale;
                @MinimapRescale.canceled += instance.OnMinimapRescale;
                @NextRadioSong.started += instance.OnNextRadioSong;
                @NextRadioSong.performed += instance.OnNextRadioSong;
                @NextRadioSong.canceled += instance.OnNextRadioSong;
                @PauseRadio.started += instance.OnPauseRadio;
                @PauseRadio.performed += instance.OnPauseRadio;
                @PauseRadio.canceled += instance.OnPauseRadio;
            }
        }
    }
    public SteeringWheelActions @SteeringWheel => new SteeringWheelActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IKeyboardActions
    {
        void OnSteering(InputAction.CallbackContext context);
        void OnBraking(InputAction.CallbackContext context);
        void OnAcceleration(InputAction.CallbackContext context);
        void OnClutch(InputAction.CallbackContext context);
        void OnShiftUP(InputAction.CallbackContext context);
        void OnShiftDOWN(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
        void OnStartEngine(InputAction.CallbackContext context);
        void OnMinimapRescale(InputAction.CallbackContext context);
        void OnNextRadioSong(InputAction.CallbackContext context);
        void OnPauseRadio(InputAction.CallbackContext context);
    }
    public interface IGamepadActions
    {
        void OnSteering(InputAction.CallbackContext context);
        void OnBraking(InputAction.CallbackContext context);
        void OnAcceleration(InputAction.CallbackContext context);
        void OnClutch(InputAction.CallbackContext context);
        void OnShiftUP(InputAction.CallbackContext context);
        void OnShiftDOWN(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
        void OnStartEngine(InputAction.CallbackContext context);
        void OnMinimapRescale(InputAction.CallbackContext context);
        void OnNextRadioSong(InputAction.CallbackContext context);
        void OnPauseRadio(InputAction.CallbackContext context);
    }
    public interface ISteeringWheelActions
    {
        void OnSteering(InputAction.CallbackContext context);
        void OnBraking(InputAction.CallbackContext context);
        void OnAcceleration(InputAction.CallbackContext context);
        void OnClutch(InputAction.CallbackContext context);
        void OnShiftUP(InputAction.CallbackContext context);
        void OnShiftDOWN(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
        void OnStartEngine(InputAction.CallbackContext context);
        void OnMinimapRescale(InputAction.CallbackContext context);
        void OnNextRadioSong(InputAction.CallbackContext context);
        void OnPauseRadio(InputAction.CallbackContext context);
    }
}
